# Generated by Django 5.2.10 on 2026-02-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationhistory',
            name='export_format',
            field=models.CharField(choices=[('preview', 'Visualização'), ('json', 'JSON'), ('csv', 'CSV')], default='preview', max_length=10),
        ),
    ]
